name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Cargo build (all targets)
        run: cargo build --all-targets --verbose
      - name: Cargo test
        run: cargo test --verbose
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Cargo build wasm target
        run: cargo build --release --target wasm32-unknown-unknown
      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli --version ^0.2
      - name: Generate wasm bindings
        run: |
          mkdir -p examples/wasm/pkg
          wasm-bindgen --target web --no-typescript \
            --out-dir examples/wasm/pkg \
            --out-name uuid45 \
            target/wasm32-unknown-unknown/release/uuid45.wasm
      - name: Upload WASM demo artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-demo
          path: examples/wasm
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Format check
        run: cargo fmt --all -- --check
